import 'package:flutter/material.dart';
import '../state/app_state.dart';
import 'overview_screen.dart';
import 'contracts/contracts_screen.dart';
import 'contracts/contract_detail_screen.dart';
import 'contracts/contract_form_screen.dart';
import 'tickets/tickets_screen.dart';
import 'tickets/ticket_form_screen.dart';
import 'tickets/ticket_detail_screen.dart';
import 'visits/visits_screen.dart';
import 'visits/visit_detail_screen.dart';
import 'finance/finance_screen.dart';
import 'finance/contract_finance_screen.dart';
import 'finance/receipts_screen.dart';
import 'finance/claims_screen.dart';
import 'finance/staff_finance_screen.dart';
import 'quotes/quotes_screen.dart';
import 'quotes/quote_form_screen.dart';
import 'inventory/inventory_screen.dart';
import 'inventory/suppliers_screen.dart';
import 'team/team_screen.dart';
import 'team/tracking_screen.dart';
import 'company/company_screen.dart';
import 'company/company_docs_screen.dart';
import 'company/client_companies_screen.dart';
import 'assets/assets_screen.dart';
import 'reports/reports_screen.dart';
import 'meetings/meetings_screen.dart';
import 'notifications_screen.dart';
import 'activity_screen.dart';
import 'ai/ai_admin_screen.dart';
import 'ai/predictions_screen.dart';
import 'ai/voice_settings_screen.dart';
import 'knowledge/knowledge_screen.dart';
import 'admin/users_screen.dart';
import 'admin/companies_screen.dart';
import 'admin/moderation_screen.dart';
import 'admin/storage_data_screen.dart';
import 'admin/data_tools_screen.dart';
import 'admin/banners_screen.dart';
import 'admin/system_screen.dart';
import 'misc/operations_screen.dart';
import 'misc/drafts_screen.dart';
import 'misc/entry_links_screen.dart';
import 'misc/whatsapp_screen.dart';
import 'misc/analytics_screen.dart';
import 'misc/my_location_screen.dart';
import 'misc/default_items_screen.dart';
import 'meetings/meeting_form_screen.dart';

/// مسجّل الصفحات: مفتاح → منشئ الصفحة.
Widget pageFor(String key) {
  final app = AppState.instance;
  switch (key) {
    case 'overview': return const OverviewScreen();
    case 'contracts': return const ContractsScreen();
    case 'contract-detail': return const ContractDetailScreen();
    case 'contract-finance': return const ContractFinanceScreen();
    case 'contract-form': return const ContractFormScreen();
    case 'tickets': return const TicketsScreen();
    case 'ticket-detail': return const TicketDetailScreen();
    case 'ticket-form': return const TicketFormScreen();
    case 'visits': return const VisitsScreen();
    case 'visit-detail': return const VisitDetailScreen();
    case 'finance': return const FinanceScreen();
    case 'receipts': return const ReceiptsScreen();
    case 'claims': return const ClaimsScreen();
    case 'staff-finance': return const StaffFinanceScreen();
    case 'quotes': return const QuotesScreen();
    case 'quote-form': return const QuoteFormScreen();
    case 'inventory': return const InventoryScreen();
    case 'suppliers': return const SuppliersScreen();
    case 'team': return const TeamScreen();
    case 'tracking': return const TrackingScreen();
    case 'company': return const CompanyScreen();
    case 'company-docs': return const CompanyDocsScreen();
    case 'client-companies': return const ClientCompaniesScreen();
    case 'company-customers': return const ClientCompaniesScreen();
    case 'assets': return const AssetsScreen();
    case 'reports': return const ReportsScreen();
    case 'meetings': return const MeetingsScreen();
    case 'meeting-form': return const MeetingFormScreen();
    case 'notifications': return const NotificationsScreen();
    case 'activity': return const ActivityScreen();
    case 'ai-admin': return const AiAdminScreen();
    case 'predictions': return const PredictionsScreen();
    case 'voice-settings': return const VoiceSettingsScreen();
    case 'knowledge-base': return const KnowledgeScreen(isHub: false);
    case 'knowledge-hub': return const KnowledgeScreen(isHub: true);
    case 'users': return const UsersScreen();
    case 'companies': return const CompaniesScreen();
    case 'moderation': return const ModerationScreen();
    case 'storage-data': return const StorageDataScreen();
    case 'data-tools': return const DataToolsScreen();
    case 'banners': return const AdminBannersScreen();
    case 'system': return const AdminSystemScreen();
    case 'operations': return const OperationsScreen();
    case 'drafts': return const DraftsScreen();
    case 'entry-links': return const EntryLinksScreen();
    case 'whatsapp': return const WhatsappScreen();
    case 'analytics': return const AnalyticsScreen();
    case 'my-location': return const MyLocationScreen();
    case 'default-items': return const DefaultItemsScreen();
    default:
      return OverviewScreen();
  }
}
