"use strict";

const amount=value=>Math.round(Number(value||0)*100)/100;
const rows=(state,key)=>Array.isArray(state[key])?state[key]:[];
function activeJournals(state){return rows(state,"misadJournalEntries").filter(row=>!row.voidedAt)}
function accountBalance(state,account){return amount(activeJournals(state).reduce((sum,journal)=>sum+(journal.lines||[]).reduce((lineSum,line)=>lineSum+(String(line.account)===String(account)?(line.side==="debit"?amount(line.amount):-amount(line.amount)):0),0),0))}
function subledger(state,key){return amount(rows(state,key).filter(row=>!row.cancelledAt).reduce((sum,row)=>sum+Math.max(0,amount(row.balance??(amount(row.total||row.amount)-amount(row.paid)))),0))}
function journalTotals(journal){return(journal.lines||[]).reduce((sum,line)=>{if(line.side==="debit")sum.debit+=amount(line.amount);if(line.side==="credit")sum.credit+=amount(line.amount);return sum},{debit:0,credit:0})}
function inspect(state){const journals=activeJournals(state),unbalanced=journals.filter(journal=>{const t=journalTotals(journal);return !(t.debit>0)||Math.abs(t.debit-t.credit)>.01}).map(row=>row.id),duplicateSources=[],seen=new Set();for(const journal of journals){if(!journal.refType||!journal.refId||journal.refType==="reversal")continue;const key=`${journal.refType}:${journal.refId}`;if(seen.has(key))duplicateSources.push(key);seen.add(key)}const receivables=subledger(state,"misadCustomerInvoices"),payables=subledger(state,"misadPurchaseInvoices"),glReceivables=accountBalance(state,"1320"),glPayables=amount(-accountBalance(state,"2100")),orphanReferences=journals.filter(journal=>{if(journal.refType==="customer-invoice")return!rows(state,"misadCustomerInvoices").some(row=>String(row.id)===String(journal.refId));if(journal.refType==="purchase-invoice")return!rows(state,"misadPurchaseInvoices").some(row=>String(row.id)===String(journal.refId));if(journal.refType==="receipt")return!rows(state,"misadReceipts").some(row=>String(row.id)===String(journal.refId));if(journal.refType==="supplier-payment")return!rows(state,"v2SupplierPayments").some(row=>String(row.id)===String(journal.refId));if(journal.refType==="payroll")return!rows(state,"misadPayrolls").some(row=>String(row.id)===String(journal.refId));return false}).map(row=>row.id);const checks={journalsBalanced:unbalanced.length===0,uniqueSourcePosting:duplicateSources.length===0,noOrphanReferences:orphanReferences.length===0,receivablesReconciled:Math.abs(receivables-glReceivables)<=.01,payablesReconciled:Math.abs(payables-glPayables)<=.01};return{ok:Object.values(checks).every(Boolean),checks,metrics:{journalCount:journals.length,receivables,glReceivables,payables,glPayables},issues:{unbalanced,duplicateSources,orphanReferences,receivablesDifference:amount(receivables-glReceivables),payablesDifference:amount(payables-glPayables)},checkedAt:new Date().toISOString()}}
module.exports={amount,accountBalance,subledger,journalTotals,inspect};
