"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto"),auth=require("./auth.cjs");
function createAuthStore(options){const file=path.join(options.dataDir,"v2","auth.json"),key=String(options.key||"");if(!key)throw new Error("V2 authentication key is required");const attempts=new Map();function read(){if(!fs.existsSync(file))return{version:1,accounts:{},revoked:{}};const value=JSON.parse(fs.readFileSync(file,"utf8"));if(!value.accounts||!value.revoked)throw new Error("V2 auth store is invalid");return value}function write(value){fs.mkdirSync(path.dirname(file),{recursive:true});const temp=`${file}.${process.pid}.${crypto.randomBytes(3).toString("hex")}.tmp`;fs.writeFileSync(temp,JSON.stringify(value),{mode:0o600});fs.renameSync(temp,file)}function rate(userId){const now=Date.now(),item=attempts.get(userId)||{count:0,from:now};if(now-item.from>15*60*1000){item.count=0;item.from=now}item.count++;attempts.set(userId,item);if(item.count>5)throw Object.assign(new Error("Too many V2 login attempts; try again later"),{status:429})}function clearRate(userId){attempts.delete(userId)}
  function enroll(identity,password){const root=read(),userId=String(identity.userId);if(root.accounts[userId]?.active)throw Object.assign(new Error("V2 account is already enrolled"),{status:409});const secret=auth.randomBase32(),codes=auth.recoveryCodes();root.accounts[userId]={userId,tenantId:String(identity.tenantId),role:String(identity.role),name:String(identity.name||""),passwordHash:auth.hashPassword(password),totpSecret:auth.seal(secret,key),recoveryHashes:codes.map(code=>crypto.createHash("sha256").update(code).digest("hex")),active:false,createdAt:new Date().toISOString()};write(root);return{secret,recoveryCodes:codes,otpauth:`otpauth://totp/${encodeURIComponent(options.issuer||"Shumoos V2")}:${encodeURIComponent(userId)}?secret=${secret}&issuer=${encodeURIComponent(options.issuer||"Shumoos V2")}`}}
  function confirm(userId,code){const root=read(),account=root.accounts[String(userId)];if(!account)throw new Error("V2 enrollment not found");if(!auth.verifyTotp(auth.unseal(account.totpSecret,key),code))throw Object.assign(new Error("Invalid MFA code"),{status:401});account.active=true;account.activatedAt=new Date().toISOString();write(root);return createSession(account)}
  function createSession(account){const session=auth.issueSession(account,key,30*60);return{token:session.token,expiresAt:new Date(session.payload.exp*1000).toISOString(),identity:{userId:account.userId,tenantId:account.tenantId,role:account.role,name:account.name}}}
  function login(userId,password,code){userId=String(userId);rate(userId);const root=read(),account=root.accounts[userId];if(!account?.active||!auth.verifyPassword(password,account.passwordHash))throw Object.assign(new Error("Invalid V2 credentials"),{status:401});const secret=auth.unseal(account.totpSecret,key);if(!auth.verifyTotp(secret,code)){const hash=crypto.createHash("sha256").update(String(code||"").toUpperCase()).digest("hex"),index=account.recoveryHashes.indexOf(hash);if(index<0)throw Object.assign(new Error("Invalid MFA code"),{status:401});account.recoveryHashes.splice(index,1);write(root)}clearRate(userId);return createSession(account)}
  function identity(token){const root=read(),payload=auth.verifySession(token,key,new Set(Object.keys(root.revoked)));if(!payload)return null;const account=root.accounts[payload.sub];return account?.active?{userId:account.userId,tenantId:account.tenantId,role:account.role,name:account.name,jti:payload.jti}:null}
  function logout(token){const root=read(),payload=auth.verifySession(token,key,new Set());if(payload){root.revoked[payload.jti]=payload.exp;const now=Math.floor(Date.now()/1000);for(const[jti,exp]of Object.entries(root.revoked))if(exp<=now)delete root.revoked[jti];write(root)}return{ok:true}}
  return{file,enroll,confirm,login,identity,logout};}
module.exports={createAuthStore};
