"use strict";
const crypto=require("crypto");
const b32="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const encode=value=>Buffer.from(value).toString("base64url"),decode=value=>Buffer.from(value,"base64url");
function hashPassword(password,salt=crypto.randomBytes(16)){const value=String(password||"");if(value.length<12||value.length>200)throw new Error("Password must be between 12 and 200 characters");const derived=crypto.scryptSync(value,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});return`scrypt$32768$${salt.toString("base64")}$${derived.toString("base64")}`}
function verifyPassword(password,stored){try{const [algorithm,n,salt,expected]=String(stored).split("$");if(algorithm!=="scrypt"||n!=="32768")return false;const actual=crypto.scryptSync(String(password),Buffer.from(salt,"base64"),64,{N:32768,r:8,p:1,maxmem:64*1024*1024}),target=Buffer.from(expected,"base64");return actual.length===target.length&&crypto.timingSafeEqual(actual,target)}catch{return false}}
function randomBase32(size=20){const bytes=crypto.randomBytes(size);let bits="";for(const byte of bytes)bits+=byte.toString(2).padStart(8,"0");let out="";for(let i=0;i<bits.length;i+=5)out+=b32[parseInt(bits.slice(i,i+5).padEnd(5,"0"),2)];return out}
function decodeBase32(value){let bits="";for(const char of String(value).replace(/=|\s/g,"").toUpperCase()){const index=b32.indexOf(char);if(index<0)throw new Error("Invalid base32 secret");bits+=index.toString(2).padStart(5,"0")}const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(bytes)}
function totp(secret,time=Date.now(),step=30){const counter=Math.floor(time/1000/step),buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const digest=crypto.createHmac("sha1",decodeBase32(secret)).update(buffer).digest(),offset=digest[digest.length-1]&15,code=(digest.readUInt32BE(offset)&0x7fffffff)%1000000;return String(code).padStart(6,"0")}
function verifyTotp(secret,code,time=Date.now()){const candidate=String(code||"").padStart(6,"0");return[-1,0,1].some(window=>{const expected=Buffer.from(totp(secret,time+window*30000));const actual=Buffer.from(candidate);return expected.length===actual.length&&crypto.timingSafeEqual(expected,actual)})}
function seal(value,key){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",crypto.createHash("sha256").update(String(key)).digest(),iv),encrypted=Buffer.concat([cipher.update(String(value),"utf8"),cipher.final()]);return`${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`}
function unseal(value,key){const [iv,tag,data]=String(value).split("."),decipher=crypto.createDecipheriv("aes-256-gcm",crypto.createHash("sha256").update(String(key)).digest(),decode(iv));decipher.setAuthTag(decode(tag));return Buffer.concat([decipher.update(decode(data)),decipher.final()]).toString("utf8")}
function issueSession(identity,key,ttlSeconds=1800){const payload={sub:String(identity.userId),tenant:String(identity.tenantId),role:String(identity.role),jti:crypto.randomUUID(),iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+ttlSeconds},body=encode(JSON.stringify(payload)),signature=crypto.createHmac("sha256",String(key)).update(body).digest("base64url");return{token:`${body}.${signature}`,payload}}
function verifySession(token,key,revoked=new Set(),now=Math.floor(Date.now()/1000)){try{const [body,signature]=String(token||"").split("."),expected=crypto.createHmac("sha256",String(key)).update(body).digest(),actual=decode(signature);if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return null;const payload=JSON.parse(decode(body).toString("utf8"));if(!payload.sub||!payload.jti||payload.exp<=now||payload.iat>now+60||revoked.has(payload.jti))return null;return payload}catch{return null}}
function recoveryCodes(count=8){return Array.from({length:count},()=>crypto.randomBytes(5).toString("hex").toUpperCase())}
module.exports={hashPassword,verifyPassword,randomBase32,decodeBase32,totp,verifyTotp,seal,unseal,issueSession,verifySession,recoveryCodes};
