"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const derive=secret=>crypto.createHash("sha256").update(String(secret)).digest();
const digest=value=>crypto.createHash("sha256").update(value).digest("hex");
function writeBackup(dir,label,value,secret){if(!secret)throw Object.assign(new Error("V2_BACKUP_KEY is required for encrypted backups"),{status:503});fs.mkdirSync(dir,{recursive:true});const plaintext=Buffer.from(JSON.stringify(value),"utf8"),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",derive(secret),iv),encrypted=Buffer.concat([cipher.update(plaintext),cipher.final()]),envelope={format:"shumoos-v2-backup",version:1,algorithm:"aes-256-gcm",createdAt:new Date().toISOString(),label,iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),ciphertext:encrypted.toString("base64"),plaintextSha256:digest(plaintext)};const file=path.join(dir,`${Date.now()}-${String(label).replace(/[^a-z0-9-]/gi,"-")}.v2bak`),temp=`${file}.${process.pid}.tmp`;fs.writeFileSync(temp,JSON.stringify(envelope),{encoding:"utf8",mode:0o600});fs.renameSync(temp,file);return{file,createdAt:envelope.createdAt,sha256:envelope.plaintextSha256}}
function readBackup(file,secret){if(!secret)throw new Error("V2_BACKUP_KEY is required to decrypt backups");const envelope=JSON.parse(fs.readFileSync(file,"utf8"));if(envelope.format!=="shumoos-v2-backup"||envelope.algorithm!=="aes-256-gcm")throw new Error("Unsupported V2 backup format");const decipher=crypto.createDecipheriv("aes-256-gcm",derive(secret),Buffer.from(envelope.iv,"base64"));decipher.setAuthTag(Buffer.from(envelope.tag,"base64"));const plaintext=Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,"base64")),decipher.final()]);if(digest(plaintext)!==envelope.plaintextSha256)throw new Error("V2 backup checksum mismatch");const value=JSON.parse(plaintext.toString("utf8"));if(!value||typeof value!=="object"||Array.isArray(value)||!value.tenants)throw new Error("V2 backup schema is invalid");return{value,envelope}}
function listBackups(dir){if(!fs.existsSync(dir))return[];return fs.readdirSync(dir).filter(name=>name.endsWith(".v2bak")).sort().reverse().map(name=>path.join(dir,name))}
function verifyLatest(dir,secret){const [file]=listBackups(dir);if(!file)return{ok:false,error:"No encrypted V2 backup exists"};try{const result=readBackup(file,secret);return{ok:true,file:path.basename(file),createdAt:result.envelope.createdAt,sha256:result.envelope.plaintextSha256,tenantCount:Object.keys(result.value.tenants).length}}catch(error){return{ok:false,file:path.basename(file),error:error.message}}}
module.exports={derive,digest,writeBackup,readBackup,listBackups,verifyLatest};
