"use strict";

const crypto=require("crypto");
const clone=value=>JSON.parse(JSON.stringify(value));
const list=(state,key)=>Array.isArray(state[key])?state[key]:(state[key]=[]);
const makeId=prefix=>`${prefix}-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
const text=(value,label,max=300)=>{const result=String(value??"").trim();if(!result)throw new Error(`${label} is required`);if(result.length>max)throw new Error(`${label} is too long`);return result};
const number=(value,label)=>{const result=Number(value);if(!Number.isFinite(result)||result<0)throw new Error(`${label} is invalid`);return Math.round(result*100)/100};
function role(ctx,allowed){if(!allowed.includes(ctx.role))throw Object.assign(new Error("Permission denied"),{status:403})}
function audit(state,ctx,action,entity,entityId,detail){list(state,"v2Audit").unshift({id:makeId("V2-AUD"),action,entity,entityId,detail,userId:ctx.userId,userName:ctx.name||"",at:new Date().toISOString(),environment:"v2"})}
function atomic(state,operation){const work=clone(state);try{const result=operation(work);Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,work);return{ok:true,...result}}catch(error){return{ok:false,error:error.message,status:error.status||400}}}
const definitions={
  customer:{collection:"v2Customers",prefix:"V2-CUS",roles:["owner","admin","company_admin","sales"],fields:(i)=>({name:text(i.name,"Name"),phone:String(i.phone||"").trim(),unifiedNumber:String(i.unifiedNumber||"").trim(),status:String(i.status||"عميل")})},
  employee:{collection:"misadCompanyStaff",prefix:"V2-EMP",roles:["owner","admin","company_admin","hr"],fields:(i)=>({name:text(i.name,"Name"),identity:text(i.identity,"Identity",30),role:text(i.role,"Role",40),baseSalary:number(i.baseSalary,"Salary"),employmentStatus:String(i.employmentStatus||"على رأس العمل")})},
  supplier:{collection:"misadSuppliers",prefix:"V2-SUP",roles:["owner","admin","company_admin","purchasing"],fields:(i)=>({name:text(i.name,"Name"),phone:String(i.phone||"").trim(),city:String(i.city||"").trim(),category:String(i.category||"").trim(),taxNumber:String(i.taxNumber||"").trim(),status:String(i.status||"نشط")})},
  "purchase-order":{collection:"v2PurchaseOrders",prefix:"V2-PO",roles:["owner","admin","company_admin","purchasing"],fields:(i)=>({supplierId:String(i.supplierId||"").trim(),supplierName:text(i.supplierName,"Supplier"),date:text(i.date,"Date",10),description:text(i.description,"Description"),total:number(i.total,"Total"),status:String(i.status||"مسودة")})},
  contract:{collection:"misadContracts",prefix:"V2-CONT",roles:["owner","admin","company_admin","sales"],fields:(i)=>({clientId:String(i.clientId||"").trim(),clientName:text(i.clientName,"Client"),type:text(i.type,"Type"),description:text(i.description,"Description"),startDate:text(i.startDate,"Start date",10),status:String(i.status||"مسودة")})},
  "work-order":{collection:"v2WorkOrders",prefix:"V2-WO",roles:["owner","admin","company_admin","dispatcher"],fields:(i)=>({clientName:text(i.clientName,"Client"),contractId:String(i.contractId||"").trim(),priority:String(i.priority||"عادي"),description:text(i.description,"Description"),scheduledAt:text(i.scheduledAt,"Date",10),status:String(i.status||"مفتوح")})}
};
function create(state,input,ctx){return atomic(state,work=>{const def=definitions[input.entity];if(!def)throw new Error("Unsupported entity");role(ctx,def.roles);const id=String(input.data?.id||makeId(def.prefix));if(list(work,def.collection).some(row=>String(row.id)===id))throw new Error("Duplicate record id");const record={id,companyOwnerId:ctx.tenantId,...def.fields(input.data||{}),createdAt:new Date().toISOString(),createdBy:ctx.userId,environment:"v2"};list(work,def.collection).unshift(record);audit(work,ctx,"create",input.entity,id,record.name||record.description||record.clientName||record.supplierName);return{record,collection:def.collection}})}
function update(state,input,ctx){return atomic(state,work=>{const def=definitions[input.entity];if(!def)throw new Error("Unsupported entity");role(ctx,def.roles);const record=list(work,def.collection).find(row=>String(row.id)===String(input.id)&&row.companyOwnerId===ctx.tenantId);if(!record)throw new Error("Record not found");if(record.archivedAt)throw new Error("Archived record cannot be edited");Object.assign(record,def.fields(input.data||{}),{updatedAt:new Date().toISOString(),updatedBy:ctx.userId});audit(work,ctx,"update",input.entity,record.id,"Controlled field update");return{record,collection:def.collection}})}
function archive(state,input,ctx){return atomic(state,work=>{const def=definitions[input.entity];if(!def)throw new Error("Unsupported entity");role(ctx,def.roles);const record=list(work,def.collection).find(row=>String(row.id)===String(input.id)&&row.companyOwnerId===ctx.tenantId);if(!record)throw new Error("Record not found");if(record.archivedAt)throw new Error("Record already archived");if(input.entity==="contract"){const linked=["misadCustomerInvoices","misadReceipts","misadClaims","misadContractExpenses"].some(key=>list(work,key).some(row=>String(row.contractId||"")===String(record.id)&&!row.cancelledAt));const journal=list(work,"misadJournalEntries").some(entry=>!entry.voidedAt&&(entry.lines||[]).some(line=>String(line.refContractId||"")===String(record.id)));if(linked||journal)throw Object.assign(new Error("Contract has active financial effects; reverse and settle them first"),{status:409})}record.archivedAt=new Date().toISOString();record.archivedBy=ctx.userId;record.archiveReason=text(input.reason,"Reason");record.status="مؤرشف";audit(work,ctx,"archive",input.entity,record.id,record.archiveReason);return{record,collection:def.collection}})}
function settings(state,input,ctx){return atomic(state,work=>{role(ctx,["owner","admin","company_admin"]);const previous=work.v2Settings||{},data=input.data||{};work.v2Settings={...previous,urgentSlaHours:number(data.urgentSlaHours,"SLA"),purchaseApprovalLimit:number(data.purchaseApprovalLimit,"Approval limit"),payrollApprovalLimit:number(data.payrollApprovalLimit||0,"Payroll approval limit"),environmentName:text(data.environmentName,"Environment name",80),isolated:true,sourceReadOnly:true,updatedAt:new Date().toISOString(),updatedBy:ctx.userId};audit(work,ctx,"update","settings","v2","Controlled settings update");return{record:work.v2Settings}})}
module.exports={definitions,create,update,archive,settings};
