"use strict";
const crypto=require("crypto"),clone=value=>JSON.parse(JSON.stringify(value)),list=(state,key)=>Array.isArray(state[key])?state[key]:(state[key]=[]),makeId=prefix=>`${prefix}-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`;
function role(ctx,allowed){if(!allowed.includes(ctx.role))throw Object.assign(new Error("Permission denied"),{status:403})}
function atomic(state,operation){const work=clone(state);try{const result=operation(work);Object.keys(state).forEach(key=>delete state[key]);Object.assign(state,work);return{ok:true,...result}}catch(error){return{ok:false,error:error.message,status:error.status||400}}}
function audit(state,ctx,action,entity,entityId,detail){list(state,"v2Audit").unshift({id:makeId("V2-AUD"),action,entity,entityId,detail,userId:ctx.userId,userName:ctx.name||"",at:new Date().toISOString(),environment:"v2"})}
function setPreference(state,input,ctx){return atomic(state,work=>{role(ctx,["owner","admin","company_admin","sales","dispatcher","technician","client"]);const channel=String(input.channel||"").trim();if(!["in-app","email","sms"].includes(channel))throw new Error("Unsupported notification channel");const subjectId=String(input.subjectId||ctx.userId),existing=list(work,"v2NotificationPreferences").find(row=>row.companyOwnerId===ctx.tenantId&&row.subjectId===subjectId&&row.channel===channel),record=existing||{id:makeId("V2-NP"),companyOwnerId:ctx.tenantId,subjectId,channel,createdAt:new Date().toISOString()};record.enabled=input.enabled===true||String(input.enabled)==="true";record.updatedAt=new Date().toISOString();record.updatedBy=ctx.userId;if(!existing)list(work,"v2NotificationPreferences").unshift(record);audit(work,ctx,"preference","notification",record.id,`${channel}:${record.enabled}`);return{record}})}
function recordDelivery(state,input,ctx){return atomic(state,work=>{role(ctx,["owner","admin","company_admin"]);const notification=list(work,"v2Notifications").find(row=>String(row.id)===String(input.notificationId)&&row.companyOwnerId===ctx.tenantId);if(!notification)throw new Error("Notification not found");if(!["queued","retrying"].includes(notification.status))throw new Error("Notification is not awaiting delivery");const status=String(input.status);if(!["delivered","failed"].includes(status))throw new Error("Invalid delivery status");notification.status=status;notification.channel=String(input.channel||"in-app");notification.providerMessageId=String(input.providerMessageId||"");notification.deliveryDetail=String(input.detail||"").slice(0,500);notification.deliveryAttempts=Number(notification.deliveryAttempts||0)+1;notification.lastAttemptAt=new Date().toISOString();if(status==="delivered")notification.deliveredAt=notification.lastAttemptAt;else notification.failedAt=notification.lastAttemptAt;audit(work,ctx,"delivery", "notification",notification.id,`${status}:${notification.channel}`);return{record:notification}})}
function exportSubject(state,input,ctx){return atomic(state,work=>{role(ctx,["owner","admin","company_admin"]);const subjectId=String(input.subjectId||"").trim();if(!subjectId)throw new Error("Subject is required");const keys=["v2Customers","misadCompanyStaff","misadContracts","misadTickets","v2WorkOrders","v2Opportunities","v2Quotes","misadCustomerInvoices","misadReceipts","v2StaffAdvances","v2StaffExpenses","misadPayrolls","v2PayrollPayments"],matches={};for(const key of keys){const rows=list(work,key).filter(row=>row.companyOwnerId===ctx.tenantId&&[row.id,row.clientId,row.customerId,row.staffId,row.createdBy,row.assignedTo].some(value=>String(value||"")===subjectId));if(rows.length)matches[key]=rows}const record={id:makeId("V2-PEX"),companyOwnerId:ctx.tenantId,subjectId,requestedBy:ctx.userId,createdAt:new Date().toISOString(),format:"json",data:matches};list(work,"v2PrivacyExports").unshift(record);audit(work,ctx,"export","privacy-subject",subjectId,`Collections ${Object.keys(matches).length}`);return{record}})}
function applyRetention(state,input,ctx){return atomic(state,work=>{role(ctx,["owner","admin"]);const cutoff=new Date(String(input.cutoff||""));if(Number.isNaN(cutoff.getTime()))throw new Error("Valid cutoff is required");const reason=String(input.reason||"").trim();if(!reason)throw new Error("Reason is required");const financial=new Set(["misadCustomerInvoices","misadPurchaseInvoices","misadReceipts","misadJournalEntries","v2SupplierPayments","v2StaffAdvances","v2StaffExpenses","misadPayrolls","v2PayrollPayments"]),targets=["v2Notifications","v2PrivacyExports"];let redacted=0,preserved=0;for(const key of targets)for(const row of list(work,key)){const stamp=new Date(row.createdAt||row.at||0);if(stamp<cutoff&&!row.retentionAppliedAt){if(financial.has(key)){preserved++;continue}for(const field of ["data","deliveryDetail","providerMessageId"])if(field in row)row[field]="[retention-redacted]";row.retentionAppliedAt=new Date().toISOString();row.retentionReason=reason;redacted++}}audit(work,ctx,"apply","retention",String(input.cutoff),`Redacted ${redacted}; preserved ${preserved}`);return{record:{cutoff:cutoff.toISOString(),redacted,preserved,financialRecordsDeleted:0}}})}
module.exports={setPreference,recordDelivery,exportSubject,applyRetention};
