"use strict";
const matrix={
  "sales-invoice.create":["owner","admin","company_admin","accountant"],"receipt.create":["owner","admin","company_admin","accountant","cashier"],"purchase-invoice.create":["owner","admin","company_admin","accountant","purchasing"],"supplier-payment.create":["owner","admin","accountant","cashier"],"payroll.accrue":["owner","admin","accountant","payroll"],"payroll.pay":["owner","admin","accountant","cashier"],"staff-advance.issue":["owner","admin","accountant","payroll","cashier"],"staff-expense.create":["owner","admin","accountant","payroll"],"journal.create":["owner","admin","accountant"],"document.cancel":["owner","admin","accountant"],"document.correct":["owner","admin","accountant"],"document.upload":["owner","admin","company_admin","accountant","payroll"],
  "entity.create":["owner","admin","company_admin","sales","hr","purchasing","dispatcher"],"entity.update":["owner","admin","company_admin","sales","hr","purchasing","dispatcher"],"entity.archive":["owner","admin","company_admin","sales","hr","purchasing","dispatcher"],"settings.update":["owner","admin","company_admin"],"approval.approve":["owner","admin","company_admin"],
  "purchase-order.approve":["owner","admin","company_admin"],"goods-receipt.create":["owner","admin","company_admin","warehouse"],"purchase-invoice.match":["owner","admin","company_admin","accountant"],"stock.issue":["owner","admin","company_admin","warehouse","technician"],"stock.reserve":["owner","admin","company_admin","warehouse","dispatcher","technician"],"stock.reservation.release":["owner","admin","company_admin","warehouse","dispatcher"],"stock.transfer":["owner","admin","company_admin","warehouse"],"stock.count":["owner","admin","company_admin","warehouse"],"stock.traceability.register":["owner","admin","company_admin","warehouse"],
  "bank-account.create":["owner","admin","company_admin","accountant"],"bank-statement.import":["owner","admin","accountant","cashier"],"bank-line.reconcile":["owner","admin","accountant","cashier"],"period.close":["owner","admin","accountant"],"period.reopen":["owner","admin"],
  "opportunity.create":["owner","admin","company_admin","sales"],"quote.create":["owner","admin","company_admin","sales"],"quote.approve":["owner","admin","company_admin"],"quote.convert":["owner","admin","company_admin","sales"],"contract.activate":["owner","admin","company_admin"],"contract.renew":["owner","admin","company_admin","sales"],"ticket.create":["owner","admin","company_admin","dispatcher","client"],"ticket.dispatch":["owner","admin","company_admin","dispatcher"],"work-order.close":["owner","admin","company_admin","dispatcher","technician"],
  "notification.preference":["owner","admin","company_admin","sales","dispatcher","technician","client"],"notification.delivery":["owner","admin","company_admin"],"privacy.export":["owner","admin","company_admin"],"retention.apply":["owner","admin"]
};
function authorize(role,command){const roles=matrix[command];if(!roles)throw Object.assign(new Error("Command has no permission policy"),{status:403});if(!roles.includes(String(role)))throw Object.assign(new Error("Permission denied by V2 policy"),{status:403});return true}
function capabilities(role){return Object.keys(matrix).filter(command=>matrix[command].includes(String(role)))}
module.exports={matrix,authorize,capabilities};
