"use strict";
const amount=value=>Math.round(Number(value||0)*100)/100,rows=(state,key)=>Array.isArray(state[key])?state[key]:[],active=state=>rows(state,"misadJournalEntries").filter(row=>!row.voidedAt);
const accountNames={1100:"الصندوق",1200:"البنوك",1320:"الذمم المدينة",1330:"ضريبة مدخلات",1400:"المخزون",1410:"سلف الموظفين",2100:"ذمم الموردين",2110:"بضاعة مستلمة غير مفوترة",2200:"رواتب مستحقة",2210:"مستحقات الموظفين",2310:"ضريبة مخرجات",3100:"حقوق الملكية",4100:"إيرادات الخدمات",4900:"إيرادات أخرى",5100:"مصروف الرواتب",5200:"مصروفات تشغيلية",5300:"تكلفة قطع العقود",5400:"مصروفات الموظفين"};
function inRange(row,filters={}){const date=String(row.date||"").slice(0,10);return(!filters.from||date>=filters.from)&&(!filters.to||date<=filters.to)}
function trialBalance(state,filters={}){const map=new Map();for(const journal of active(state).filter(row=>inRange(row,filters)))for(const line of journal.lines||[]){const key=String(line.account),item=map.get(key)||{account:key,name:accountNames[key]||key,debit:0,credit:0};item[line.side]=amount(item[line.side]+amount(line.amount));map.set(key,item)}return[...map.values()].sort((a,b)=>a.account.localeCompare(b.account)).map(item=>({...item,balance:amount(item.debit-item.credit)}))}
function incomeStatement(state,filters={}){const trial=trialBalance(state,filters),revenue=amount(trial.filter(row=>row.account.startsWith("4")).reduce((sum,row)=>sum+row.credit-row.debit,0)),expenses=amount(trial.filter(row=>row.account.startsWith("5")).reduce((sum,row)=>sum+row.debit-row.credit,0));return{revenue,expenses,netIncome:amount(revenue-expenses),accounts:trial.filter(row=>/^[45]/.test(row.account))}}
function balanceSheet(state,filters={}){const trial=trialBalance(state,filters),assets=amount(trial.filter(row=>row.account.startsWith("1")).reduce((sum,row)=>sum+row.debit-row.credit,0)),liabilities=amount(trial.filter(row=>row.account.startsWith("2")).reduce((sum,row)=>sum+row.credit-row.debit,0)),equity=amount(trial.filter(row=>row.account.startsWith("3")).reduce((sum,row)=>sum+row.credit-row.debit,0)),netIncome=incomeStatement(state,filters).netIncome;return{assets,liabilities,equity,retainedEarnings:netIncome,liabilitiesAndEquity:amount(liabilities+equity+netIncome),difference:amount(assets-liabilities-equity-netIncome)}}
function aging(state,key,asOf=new Date().toISOString().slice(0,10)){const day=86400000,target=new Date(`${asOf}T12:00:00Z`).getTime(),buckets={current:0,days31to60:0,days61to90:0,over90:0};const items=rows(state,key).filter(row=>!row.cancelledAt&&amount(row.balance??amount(row.total)-amount(row.paid))>0).map(row=>{const balance=amount(row.balance??amount(row.total)-amount(row.paid)),age=Math.max(0,Math.floor((target-new Date(`${String(row.date||asOf).slice(0,10)}T12:00:00Z`).getTime())/day)),bucket=age<=30?"current":age<=60?"days31to60":age<=90?"days61to90":"over90";buckets[bucket]=amount(buckets[bucket]+balance);return{id:row.id,partyId:row.clientId||row.supplierId||"",partyName:row.clientName||row.supplierName||"",date:row.date,balance,age,bucket}});return{asOf,buckets,total:amount(items.reduce((sum,row)=>sum+row.balance,0)),items}}
function employeeLedger(state,staffId){const entries=[];for(const journal of active(state))for(const line of journal.lines||[])if(String(line.refStaffId||"")===String(staffId))entries.push({journalId:journal.id,date:journal.date,description:journal.description,account:line.account,debit:line.side==="debit"?amount(line.amount):0,credit:line.side==="credit"?amount(line.amount):0});return{staffId,entries,balance:amount(entries.reduce((sum,row)=>sum+row.debit-row.credit,0))}}
function contractProfitability(state,contractId){let revenue=0,cost=0;for(const journal of active(state))for(const line of journal.lines||[])if(String(line.refContractId||"")===String(contractId)){if(String(line.account).startsWith("4"))revenue+=line.side==="credit"?amount(line.amount):-amount(line.amount);if(String(line.account).startsWith("5"))cost+=line.side==="debit"?amount(line.amount):-amount(line.amount)}return{contractId,revenue:amount(revenue),cost:amount(cost),grossProfit:amount(revenue-cost),margin:revenue?amount((revenue-cost)/revenue*100):0}}
function generate(state,type,filters={}){if(type==="trial-balance")return{type,rows:trialBalance(state,filters)};if(type==="income-statement")return{type,...incomeStatement(state,filters)};if(type==="balance-sheet")return{type,...balanceSheet(state,filters)};if(type==="receivables-aging")return{type,...aging(state,"misadCustomerInvoices",filters.asOf)};if(type==="payables-aging")return{type,...aging(state,"misadPurchaseInvoices",filters.asOf)};if(type==="employee-ledger")return{type,...employeeLedger(state,filters.staffId)};if(type==="contract-profitability")return{type,...contractProfitability(state,filters.contractId)};throw Object.assign(new Error("Unknown report type"),{status:404})}
module.exports={accountNames,trialBalance,incomeStatement,balanceSheet,aging,employeeLedger,contractProfitability,generate};
